import { useMemo } from 'react';
import type { DemoData } from '../shared/types';

interface Props {
  videoBlob: Blob;
  videoUrl: string;
  demo: DemoData;
}

function generateMarkdownContent(demo: DemoData): string {
  let md = `# ${demo.title || 'Demo Walkthrough'}\n\n`;

  md += `> Generated by HackDemo\n\n`;

  for (const step of demo.steps) {
    md += `## Step ${step.index + 1}: ${step.description}\n\n`;

    if (step.narration) {
      md += `${step.narration}\n\n`;
    }

    if (step.screenshotUrl) {
      md += `![Step ${step.index + 1}](${step.screenshotUrl})\n\n`;
    }

    md += `---\n\n`;
  }

  return md;
}

export default function DownloadBar({ videoBlob, videoUrl, demo }: Props) {
  const markdownContent = useMemo(() => generateMarkdownContent(demo), [demo]);
  const markdownBlob = useMemo(
    () => new Blob([markdownContent], { type: 'text/markdown' }),
    [markdownContent]
  );
  const markdownUrl = useMemo(() => URL.createObjectURL(markdownBlob), [markdownBlob]);

  const handleDownloadVideo = () => {
    const a = document.createElement('a');
    a.href = videoUrl;
    a.download = 'demo.mp4';
    a.click();
  };

  const handleDownloadMarkdown = () => {
    const a = document.createElement('a');
    a.href = markdownUrl;
    a.download = 'demo.md';
    a.click();
  };

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-4">
      <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
        <span>📥</span> Downloads
      </h3>
      <div className="flex gap-3">
        <button
          onClick={handleDownloadVideo}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-hack-primary hover:bg-indigo-600 rounded-lg text-sm font-medium transition-colors"
        >
          <span>🎬</span>
          <span>Download MP4</span>
          <span className="text-xs text-indigo-200 ml-1">
            ({(videoBlob.size / (1024 * 1024)).toFixed(1)} MB)
          </span>
        </button>
        <button
          onClick={handleDownloadMarkdown}
          className="flex items-center gap-2 px-4 py-2.5 bg-gray-100 hover:bg-gray-200 border border-gray-700 rounded-lg text-sm transition-colors"
        >
          <span>📝</span>
          <span>Download Markdown</span>
        </button>
      </div>
    </div>
  );
}
