import type { DemoData } from '../shared/types';

/**
 * Generate Markdown documentation from demo data.
 */
export function generateMarkdown(demo: DemoData): string {
  let md = `# ${demo.title || 'Demo Walkthrough'}\n\n`;

  md += `> Generated by HackDemo\n\n`;

  for (const step of demo.steps) {
    md += `## Step ${step.index + 1}: ${step.description}\n\n`;

    if (step.narration) {
      md += `${step.narration}\n\n`;
    }

    if (step.screenshotUrl) {
      md += `![Step ${step.index + 1}](${step.screenshotUrl})\n\n`;
    }

    if (step.pageUrl) {
      md += `*Page: ${step.pageUrl}*\n\n`;
    }

    md += `---\n\n`;
  }

  return md;
}

/**
 * Create a downloadable Blob from Markdown content.
 */
export function createMarkdownBlob(content: string): Blob {
  return new Blob([content], { type: 'text/markdown;charset=utf-8' });
}
